package com.sge.modulos.administracion.formularios;

import com.google.gson.Gson;
import com.sge.base.formularios.frameBase;
import com.sge.modulos.administracion.clases.Menu;
import com.sge.modulos.administracion.clases.Perfil;
import com.sge.modulos.administracion.cliente.cliAdministracion;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTree;
import javax.swing.SwingWorker;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeCellRenderer;

/**
 *
 * @author elderson
 */
public class perMenu extends frameBase<Menu> {

    /**
     * Creates new form perMenu
     */
    public perMenu(int modo) {
        initComponents();
        Init(modo, "");
    }

    public perMenu(int modo, String filtro) {
        initComponents();
        Init(modo, filtro);
    }

    private int modo;

    private String filtro;

    public void Init(int modo, String filtro) {
        this.modo = modo;
        this.filtro = filtro;
        OcultarControl(treeMenus);
        new swObtenerPerfiles().execute();
    }

    public class swObtenerPerfiles extends SwingWorker<Object, Object> {

        @Override
        protected Object doInBackground() throws Exception {
            VerCargando(frame);
            cliAdministracion cliente = new cliAdministracion();
            String json = "";
            try {
                json = cliente.ObtenerPerfiles(new Gson().toJson(filtro));
            } catch (Exception e) {
                OcultarCargando(frame);
                cancel(false);
                ControlarExcepcion(e);
            } finally {
                cliente.close();
            }
            return json;
        }

        @Override
        protected void done() {
            try {
                String json = get().toString();
                String[] resultado = new Gson().fromJson(json, String[].class);

                if (resultado[0].equals("true")) {
                    Perfil[] perfiles = new Gson().fromJson(resultado[1], Perfil[].class);
                    cboPerfiles.removeAllItems();
                    for (Perfil perfil : perfiles) {
                        cboPerfiles.addItem(perfil);
                    }
                }
                OcultarCargando(frame);
            } catch (Exception e) {
                OcultarCargando(frame);
                ControlarExcepcion(e);
            }
        }
    }

    public class swObtenerMenusPorPerfil extends SwingWorker<Object, Object> {

        @Override
        protected Object doInBackground() throws Exception {
            VerCargando(frame);
            MostrarControl(treeMenus);
            cliAdministracion cliente = new cliAdministracion();
            String json = "";
            try {
                Perfil perfil = (Perfil) cboPerfiles.getSelectedItem();
                json = cliente.ObtenerMenusPorPerfil(new Gson().toJson(perfil.getIdPerfil()));
            } catch (Exception e) {
                OcultarCargando(frame);
                cancel(false);
                ControlarExcepcion(e);
            } finally {
                cliente.close();
            }
            return json;
        }

        @Override
        protected void done() {
            try {
                String json = get().toString();
                String[] resultado = new Gson().fromJson(json, String[].class);
                if (resultado[0].equals("true")) {
                    Menu[] menus = new Gson().fromJson(resultado[1], Menu[].class);
                    DefaultMutableTreeNode root = new DefaultMutableTreeNode("PANTALLAS");
                    for (Menu menu : menus) {
                        DefaultMutableTreeNode nivel1 = new DefaultMutableTreeNode(menu);
                        for (Menu subMenu : menu.getSubMenus()) {
                            DefaultMutableTreeNode nivel2 = new DefaultMutableTreeNode(subMenu);
                            for (Menu subSubMenu : subMenu.getSubMenus()) {
                                DefaultMutableTreeNode nivel3 = new DefaultMutableTreeNode(subSubMenu);
                                nivel2.add(nivel3);
                            }
                            nivel1.add(nivel2);
                        }
                        root.add(nivel1);
                    }
                    treeMenus.setModel(new DefaultTreeModel(root, false));
                }
                OcultarCargando(frame);
            } catch (Exception e) {
                OcultarCargando(frame);
                ControlarExcepcion(e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame = new javax.swing.JPanel();
        pnlTitulo1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        cboPerfiles = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeMenus = new javax.swing.JTree();

        setClosable(true);

        frame.setBackground(java.awt.Color.white);
        frame.setBorder(null);

        pnlTitulo1.setBackground(new java.awt.Color(67, 100, 130));
        pnlTitulo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitulo1.setForeground(java.awt.Color.white);
        lblTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sge/base/imagenes/show-property-16.png"))); // NOI18N
        lblTitulo1.setText("PERMISOS DE MENUS");

        javax.swing.GroupLayout pnlTitulo1Layout = new javax.swing.GroupLayout(pnlTitulo1);
        pnlTitulo1.setLayout(pnlTitulo1Layout);
        pnlTitulo1Layout.setHorizontalGroup(
            pnlTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
        );
        pnlTitulo1Layout.setVerticalGroup(
            pnlTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblPerfil.setText("PERFIL");

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sge/base/imagenes/view-16.png"))); // NOI18N
        btnVer.setToolTipText("REFRESCAR");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        treeMenus.setEditable(true);
        treeMenus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMenusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treeMenus);

        javax.swing.GroupLayout frameLayout = new javax.swing.GroupLayout(frame);
        frame.setLayout(frameLayout);
        frameLayout.setHorizontalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(frameLayout.createSequentialGroup()
                        .addComponent(lblPerfil)
                        .addGap(36, 36, 36)
                        .addComponent(cboPerfiles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(262, 262, 262))
        );
        frameLayout.setVerticalGroup(
            frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameLayout.createSequentialGroup()
                .addComponent(pnlTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPerfil)
                        .addComponent(cboPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkChange(javax.swing.event.ChangeEvent evt) {                                              
        // TODO add your handling code here:
        JCheckBox check = (JCheckBox)evt.getSource();
        if(check.isSelected()){
            
        }
    }     
    
    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        treeMenus.setCellRenderer(new TreeCellRenderer() {

            @Override
            public Component getTreeCellRendererComponent(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {
                Object object = ((DefaultMutableTreeNode) value).getUserObject();
                JCheckBox check = new JCheckBox();
                if (object instanceof Menu) {
                    Menu menu = (Menu) object;
                    check = new JCheckBox(menu.getNombre(), menu.isCheck());
                }
                check.addChangeListener(new javax.swing.event.ChangeListener() {
                    public void stateChanged(javax.swing.event.ChangeEvent evt) {
                        checkChange(evt);
                    }
                });
                return check; //To change body of generated methods, choose Tools | Templates.
            }
        });
        new swObtenerMenusPorPerfil().execute();
    }//GEN-LAST:event_btnVerActionPerformed

    private void treeMenusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMenusMouseClicked
        // TODO add your handling code here:
//        DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeMenus.getLastSelectedPathComponent();
//        if (node != null) {
//            Menu menu = (Menu) node.getUserObject();
//            menu.setNombre("xxx");
//            treeMenus.updateUI();
//            System.out.print("");
//        }
    }//GEN-LAST:event_treeMenusMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox cboPerfiles;
    private javax.swing.JPanel frame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel pnlTitulo1;
    private javax.swing.JTree treeMenus;
    // End of variables declaration//GEN-END:variables
}
