package com.sge.base.formularios;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author elderson
 */
public class framePreload extends javax.swing.JPanel {

    /**
     * Creates new form frameCargando
     */
    public framePreload() {
        initComponents();
    }

    public void AgregarFrame(JPanel frame){
        pnlFrame.setLayout(new BorderLayout());
        pnlFrame.add(frame);
    }
    
    public void VerCargando(){
        ImageIcon iconoCargando = new ImageIcon(getClass().getResource("/com/sge/base/imagenes/preload-24.gif"));
        lblPreload.setText("Cargando, espere un momento por favor...");
        lblPreload.setIcon(iconoCargando);
        pnlPreload.setVisible(true);
        pnlFrame.setVisible(false);
    }
    
    public void VerProcesando(){
        ImageIcon iconoProcesando = new ImageIcon(getClass().getResource("/com/sge/base/imagenes/process-32.gif"));
        lblPreload.setText("Procesando...");
        lblPreload.setIcon(iconoProcesando);
        pnlPreload.setVisible(true);
        pnlFrame.setVisible(false);
    }
    
    public void Ocultar(){
        pnlPreload.setVisible(false);
        pnlFrame.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPreload = new javax.swing.JPanel();
        lblPreload = new javax.swing.JLabel();
        pnlFrame = new javax.swing.JPanel();

        pnlPreload.setBackground(java.awt.Color.white);
        pnlPreload.setLayout(new java.awt.BorderLayout());

        lblPreload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlPreload.add(lblPreload, java.awt.BorderLayout.CENTER);

        pnlFrame.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout pnlFrameLayout = new javax.swing.GroupLayout(pnlFrame);
        pnlFrame.setLayout(pnlFrameLayout);
        pnlFrameLayout.setHorizontalGroup(
            pnlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        pnlFrameLayout.setVerticalGroup(
            pnlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPreload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPreload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPreload;
    private javax.swing.JPanel pnlFrame;
    private javax.swing.JPanel pnlPreload;
    // End of variables declaration//GEN-END:variables
}
